id: IA97A942A
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:10:09.689199
last_modified: 2023-02-08 15:10:09.689322
source_metadata:
  title: Laṅkāvatārasūtra
  language: en
bases:
  288A:
    base_file: 288A.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
